### ISSUE TITLE
[DEG] MySQL에 넣기 전 데이터 전처리 작업

### ISSUE THREAD

**Issue by Nagyeomhan** [och5351/Bigdata_busan#18]
하겠습니다.

**Comment by och5351** [comment]
작업 전 상세 내역 공유 부탁드립니다.

어떻게 로컬 데이터를 DB 에 넣으실지 기술 및 계획 내역을 컨텐츠에 담아주세요.

**Comment by Nagyeomhan** [comment]
앞으로는 이슈를 올릴 때 더욱 자세히 작성하겠습니다!

[ 10/11 작업할 내용 ]
1. pandas로 데이터프레임을 전처리한 후, SQL Alchemy로 DDL문을 이용해 MySQL에 데이터를 담습니다.
2. 다음과 같은 형식으로 담겠습니다.
    schema명 : chromate
      - table명 : (1) 환경변수       csv파일  :  variable
                       (2) Error Lot list  csv파일  :  errorlot
                       (3) 이미지          png파일 :  img
3. img 파일을 담는 것 까지가 오늘의 목표이고,
   환경변수와 Error Lot list를 어떻게 연관시킬지는 더 생각해본 후에 작업을 하겠습니다.

**Comment by Nagyeomhan** [comment]
10/11 작업분량은 feature/#18에만 커밋을 해두었습니다.

[ 10/12 작업할 내용 ]

1. Time 컬럼이 오후 4:29:54.0 이런 형식으로 되어있으므로 16:29:54.0 으로 변환
2. 이미지 데이터 MySQL에 올리기
3. MySQL에서 직접 create schema create table 하지 않고, python 상에서 바로바로 dataframe을 SQL에 올릴 수 있는 방법 찾아서 올리기

**Comment by Nagyeomhan** [comment]
**[ 10/13 기준 남은 task 정리 ]**

1. img 테이블 만들어서 img 올리기

2. 그 다음에 들어올 파일들을 위해 코드 짜주기 (데이터베이스가 유지될 수 있도록 관리 차원)
- variable 폴더 안에 그 다음에 들어올 자료들 바로바로 SQL에 insert할 수 있도록 코드 만들기(아마 함수 형태)
- error 폴더 안에 그 다음에 들어올 자료들 바로바로 SQL에 insert할 수 있도록 코드 만들기(아마 함수 형태)
- img 폴더 안에 그 다음에 들어올 자료들 바로바로 SQL에 insert할 수 있도록 코드 만들기(아마 함수 형태)

3. DB에 저장된 데이터들을 모델 input 형식에 맞춰 바로바로 형식을 만들어낼 수 있도록 코드 만들기(아마 함수 형태)

**Comment by Nagyeomhan** [comment]
SQL에 이미지 input은 따로 이슈를 만들겠습니다.
