### ISSUE TITLE
[BCK] 로그인 및 회원가입 화면 구현

### ISSUE THREAD

**Issue by eoruadl** [och5351/Bigdata_busan#37]
메인 페이지를 로그인 화면
회원가입 버튼을 통해 회원가입 화면으로 이동 구현
MySQL 데이터베이스 연동하여 사용자 정보 저장

**Comment by och5351** [comment]
회원가입은 MySQL 에 데이터를 저장하기 전에 스키마부터 작성을 하는 연습 하셔야 합니다.
정형 데이터로 존재하기 어렵다고 판단 되시면 MongoDB 를 활용하여 반정형 데이터로 저장이 가능합니다.

가능하면 JWT 라는 개념을 찾아서 알아보시고 이번 주 토요일에 리뷰하실 때 알려주시면 좋을 듯 합니다.

**Comment by eoruadl** [comment]
댓글 내용을 이제 확인했습니다.
스키마 같은 경우는 MySQL workbench로 만들어보았고
일단 현재 이름 비밀번호 이메일 세개의 열로만 이루어진 테이블로 사용자 데이터를 저장해보았습니다.
나중에 회원가입 시 추가될  내용들이 생기게 될건데 그에 맞게 다시 생각해보도록 하겠습니다.

JWT 개념은 이번주 중에 알아보도록 하겠습니다.
